variables:
  - name: E_c
    initial_point_factor: 1.00
    dist:
      name: sgld_lower_t
      params:
        sigma: 0.0069132641498648
        r: 0.842595342406661
        theta: 9.31796423264929
        b: -8.31853610727804
        x_lower_limit: 0.00
        scale_factor: 1.190e+10

  - name: poisson_c
    initial_point_factor: 1.00
    dist:
      name: sgld_lower_upper_t
      params:
        sigma: 0.019041419294554
        r: 1.11109627493899
        theta: 6.03636936803434
        b: -5.03828207218081
        x_lower_limit: 0.00
        x_upper_limit: 0.49
        scale_factor: 0.18

  - name: cohesion_c
    initial_point_factor: 1.00
    dist:
      name: lognormal
      params:
        mean: 1.0
        cov: 0.1

  - name: friction_angle_c
    initial_point_factor: 1.00
    dist:
      name: weibull_min
      params:
        mean: 1.0
        cov: 0.1795

  - name: thermal_expansion_c
    initial_point_factor: 1.00
    dist:
      name: sgld_lower_t
      params:
        sigma: 0.065809372048842
        r: 1.40970309731791
        theta: 2.18480905289523
        b: -1.19118806087838
        x_lower_limit: 0.00
        scale_factor: 6.400e-06


  - name: thermal_conductivity_c
    initial_point_factor: 1.00
    dist:
      name: sgld_lower_t
      params:
        sigma: 0.041723058962085
        r: 0.845230806830142
        theta: 0.611291540276027
        b: 0.387344837476029
        x_lower_limit: 0.00
        scale_factor: 1.950e+00


  - name: volumetric_heat_capacity_c
    initial_point_factor: 1.00
    dist:
      name: sgld
      params:
        sigma: 0.036969080601851
        r: 1.1481086920259
        theta: 0.054383037624119
        b: 0.945554473714374

  - name: internal_pressure
    initial_point_factor: 1.00
    dist:
      name: gumbel_r
      params:
        mean: 1.0
        cov: 0.10

  - name: internal_temperature
    initial_point_factor: 1.00
    dist:
      name: normal
      params:
        mean: 1.0
        cov: 0.10

config:
  result_files: "txt"
  form:
    beta: 20.0
    delta: 0.01
    gamma: 0.00
    tol:  1e-03
    maxit: 100
    Nr: 1
  monte_carlo:
    n_samples: 30000
    batch_size: 50
    seed: 1234

mesh:
  casing_internal_diameter: 0.31432
  casing_external_diameter: 0.34608
  well_diameter: 0.4191
